apiVersion: v1
kind: Secret
metadata:
  name: {{ template "atlas-pubsub.fullname" . }}
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey }}
