apiVersion: v1
appVersion: 0.2.2
description: A Helm chart for Kubernetes
name: atlas-pubsub
keywords:
- atlas
- pubsub
sources:
- https://github.com/infobloxopen/atlas-pubsub
version: 0.1.0
home: https://github.com/infobloxopen/atlas-pubsub
maintainers:
- name: ZachEddy
  email: zeddy@infoblox.com
- name: mkam423
  email: mkam@infoblox.com
